// Slang imposter packs — one per decade. Each round samples 3 natives + 1
// imposter from a pack, shuffles, and asks the player to spot the misfit.

export const IMPOSTER_PACKS = [
  {
    id: "1920s",
    decade: 1920,
    title: "Slang of the 1920s",
    natives: [
      { name: "bee's knees", note: "1920s flapper-era superlative" },
      { name: "cat's pajamas", note: "the same animal-anatomy craze, 1920s" },
      { name: "applesauce", note: "1920s exclamation for nonsense" },
      { name: "horsefeathers", note: "1920s — Marx Brothers popularized it" },
      { name: "speakeasy", note: "Prohibition-era unlicensed bar, 1920s" },
      { name: "hooch", note: "1920s — moonshine post-Volstead" },
      { name: "giggle water", note: "1920s slang for champagne" },
      { name: "sheik", note: "1920s — dapper man, post-Valentino" },
      { name: "sheba", note: "1920s — the female sheik" },
      { name: "bunk", note: "1920s — Henry Ford: 'history is bunk'" },
    ],
    imposters: [
      { name: "hep", note: "1940s swing-era jazz" },
      { name: "scram", note: "1930s gangster pulp" },
      { name: "dame", note: "1940s noir-era" },
      { name: "groovy", note: "actually 1940s jazz, not 1920s" },
      { name: "jalopy", note: "1950s teen hot-rod" },
    ],
  },
  {
    id: "1930s",
    decade: 1930,
    title: "Slang of the 1930s",
    natives: [
      { name: "bindle", note: "1930s hobo's bedroll" },
      { name: "hobo", note: "1930s — peaked during the Depression" },
      { name: "breadline", note: "1930s soup-kitchen queue" },
      { name: "Hooverville", note: "1930s — Depression-era shantytown" },
      { name: "flophouse", note: "1930s cheap lodging" },
      { name: "palooka", note: "1930s — mediocre boxer" },
      { name: "gumshoe", note: "1930s — pulp-era detective" },
      { name: "mug", note: "1930s pulp — fellow / face" },
      { name: "scram", note: "1930s gangster-era 'beat it'" },
      { name: "lollygag", note: "1930s — to dawdle" },
    ],
    imposters: [
      { name: "hep", note: "1940s swing era" },
      { name: "groovy", note: "1940s jazz" },
      { name: "daddy-o", note: "1950s beat-era" },
      { name: "skedaddle", note: "1860s Civil War origin" },
      { name: "swell", note: "much earlier — 1900s already" },
    ],
  },
  {
    id: "1940s",
    decade: 1940,
    title: "Slang of the 1940s",
    natives: [
      { name: "hep", note: "1940s pre-WWII jazz adjective" },
      { name: "jive", note: "1940s swing-era talk" },
      { name: "groovy", note: "1940s — 'in the groove' jazz lingo" },
      { name: "wisecrack", note: "1940s pulp / Algonquin echo" },
      { name: "dame", note: "1940s noir-era" },
      { name: "snafu", note: "1940s — military acronym" },
      { name: "zoot suit", note: "1940s — high-waist, wide-leg suit" },
      { name: "swell", note: "1940s talkie-era exclamation" },
      { name: "gangster", note: "1940s noir staple" },
      { name: "rumble", note: "1940s gang-fight term" },
    ],
    imposters: [
      { name: "daddy-o", note: "1950s bebop hipster" },
      { name: "far out", note: "1960s–70s hippie / beat" },
      { name: "psychedelic", note: "1960s coinage, peaked 70s" },
      { name: "groovy is fine — replace if needed", note: "1940s actually native" },
      { name: "mellow", note: "1970s singer-songwriter era" },
      { name: "beatnik", note: "1958 coinage, 60s peak" },
    ],
  },
  {
    id: "1950s",
    decade: 1950,
    title: "Slang of the 1950s",
    natives: [
      { name: "daddy-o", note: "1950s bebop address" },
      { name: "hipster", note: "1950s — Mailer's 'White Negro' era" },
      { name: "dig", note: "1950s — 'dig it,' bebop origin" },
      { name: "square", note: "1950s — uncool, conductor's beat pattern" },
      { name: "kicks", note: "1950s — Kerouac's currency" },
      { name: "drag", note: "1950s beat-era 'what a drag'" },
      { name: "fink", note: "1950s — informer, McCarthy era" },
      { name: "gasser", note: "1950s — 'a real gasser'" },
      { name: "gone", note: "1950s — 'real gone, man'" },
      { name: "beatnik", note: "1958 — Herb Caen coinage" },
    ],
    imposters: [
      { name: "groovy", note: "1940s jazz origin (peak earlier)" },
      { name: "far out", note: "1970s mass-print peak" },
      { name: "psychedelic", note: "1960s–70s" },
      { name: "trippy", note: "1970s LSD-era" },
      { name: "rad", note: "1980s skater" },
    ],
  },
  {
    id: "1960s",
    decade: 1960,
    title: "Slang of the 1960s",
    natives: [
      { name: "far out", note: "1960s — beat-to-hippie crossover" },
      { name: "outta sight", note: "1960s soul / R&B" },
      { name: "psychedelic", note: "1960s — coined 1957, era-defining" },
      { name: "groovy", note: "1960s — flower-power adoption" },
      { name: "hippie", note: "1960s — counterculture core" },
      { name: "flower child", note: "1960s post-Summer-of-Love" },
      { name: "right on", note: "1960s — Black Power affirmation" },
      { name: "uptight", note: "1960s — Stevie Wonder hit, 1965" },
      { name: "trip", note: "1960s — LSD / acid-test era" },
      { name: "bummer", note: "1960s bad-trip origin" },
    ],
    imposters: [
      { name: "rad", note: "1980s skater" },
      { name: "gnarly", note: "1980s surfer / valley" },
      { name: "tubular", note: "1980s valley" },
      { name: "bodacious", note: "1980s revival" },
      { name: "awesome", note: "1990s mass-print peak" },
    ],
  },
  {
    id: "1970s",
    decade: 1970,
    title: "Slang of the 1970s",
    natives: [
      { name: "boogie", note: "1970s disco-era reborn" },
      { name: "funky", note: "1970s — P-funk / soul" },
      { name: "mellow", note: "1970s — singer-songwriter chill" },
      { name: "foxy", note: "1970s — Jimi Hendrix's 'Foxy Lady'" },
      { name: "righteous", note: "1970s — earnest enthusiasm" },
      { name: "dyno-mite", note: "1970s — Jimmie Walker on Good Times" },
      { name: "copacetic", note: "1970s — fine, satisfactory" },
      { name: "jive turkey", note: "1970s — full of nonsense" },
      { name: "right on", note: "1970s — mass-print peak" },
      { name: "bell-bottoms", note: "1970s fashion-as-slang" },
    ],
    imposters: [
      { name: "rad", note: "1980s skater" },
      { name: "gnarly", note: "1980s surfer" },
      { name: "tubular", note: "1980s valley" },
      { name: "bogus", note: "1990s — Bill & Ted era" },
      { name: "yuppie", note: "1980s coinage" },
    ],
  },
  {
    id: "1980s",
    decade: 1980,
    title: "Slang of the 1980s",
    natives: [
      { name: "rad", note: "1980s — short for radical, skate origin" },
      { name: "gnarly", note: "1980s surfer / valley" },
      { name: "tubular", note: "1980s — hollow-wave surfer term" },
      { name: "gag me with a spoon", note: "1980s Valspeak" },
      { name: "grody", note: "1980s — 'grody to the max'" },
      { name: "yuppie", note: "1980s — Young Urban Professional" },
      { name: "preppy", note: "1980s — Lisa Birnbach handbook 1980" },
      { name: "bodacious", note: "1980s — bold + audacious" },
      { name: "psyched", note: "1980s — pumped, excited" },
      { name: "totally", note: "1980s valley intensifier" },
    ],
    imposters: [
      { name: "groovy", note: "1940s jazz / 60s revival" },
      { name: "awesome", note: "actually 1990s mass-print peak" },
      { name: "bogus", note: "1990s — Bill & Ted '89" },
      { name: "whatever", note: "1990s teen dismissal" },
      { name: "lit", note: "2010s superlative" },
    ],
  },
  {
    id: "1990s",
    decade: 1990,
    title: "Slang of the 1990s",
    natives: [
      { name: "all that", note: "1990s — 'she thinks she's all that'" },
      { name: "da bomb", note: "1990s superlative" },
      { name: "phat", note: "1990s — Pretty Hot And Tempting" },
      { name: "fly", note: "1990s hip-hop adjective" },
      { name: "dope", note: "1990s — positive adjective peak" },
      { name: "wack", note: "1990s — opposite of dope" },
      { name: "chillin'", note: "1990s — Will Smith era" },
      { name: "homie", note: "1990s — from homeboy" },
      { name: "buggin'", note: "1990s NYC — 'you're buggin'" },
      { name: "as if", note: "1990s — Clueless 1995" },
      { name: "whatever", note: "1990s teen dismissal" },
    ],
    imposters: [
      { name: "lit", note: "2010s — late slang superlative" },
      { name: "swag", note: "2010s — post-Bieber" },
      { name: "bae", note: "2010s — Before Anyone Else" },
      { name: "groovy", note: "1940s jazz" },
      { name: "rad", note: "1980s skater" },
    ],
  },
  {
    id: "2000s",
    decade: 2000,
    title: "Slang of the 2000s",
    natives: [
      { name: "bling", note: "2000s — Cash Money Records 1999 single" },
      { name: "crunk", note: "2000s southern hip-hop" },
      { name: "ballin'", note: "2000s — living large" },
      { name: "holla", note: "2000s — call out / shout" },
      { name: "off the chain", note: "2000s — wild, excellent" },
      { name: "tight", note: "2000s — cool, cohesive" },
      { name: "beef", note: "2000s — feud / grudge" },
      { name: "diss", note: "2000s — disrespect, mass-print peak" },
      { name: "boo-yah", note: "2000s — exclamation of triumph" },
      { name: "hella", note: "2000s — Bay Area intensifier" },
    ],
    imposters: [
      { name: "lit", note: "2010s superlative" },
      { name: "on fleek", note: "2014 Vine peak" },
      { name: "bae", note: "2010s" },
      { name: "yolo", note: "2011 — Drake's 'The Motto'" },
      { name: "groovy", note: "1940s jazz" },
    ],
  },
  {
    id: "2010s",
    decade: 2010,
    title: "Slang of the 2010s",
    natives: [
      { name: "yolo", note: "2011 — Drake's 'The Motto'" },
      { name: "selfie", note: "2010s — Oxford WoY 2013" },
      { name: "twerk", note: "2010s — VMA 2013 peak" },
      { name: "bae", note: "2010s — Before Anyone Else" },
      { name: "on fleek", note: "2014 Vine — Peaches Monroee" },
      { name: "lit", note: "2010s superlative" },
      { name: "woke", note: "2010s — AAVE since 30s, mainstreamed" },
      { name: "basic", note: "2010s — pumpkin-spice-latte era" },
      { name: "vape", note: "2014 — Oxford WoY" },
      { name: "salty", note: "2010s — bitter / petty" },
    ],
    imposters: [
      { name: "groovy", note: "1940s jazz" },
      { name: "rad", note: "1980s skater" },
      { name: "gnarly", note: "1980s surfer" },
      { name: "dope", note: "1990s peak" },
      { name: "bling", note: "2000s — Cash Money" },
    ],
  },
];
