// Imposter mode packs. Each pack: a theme, a pool of natives (true to the era),
// and a pool of imposters (close-call entries from a different era). At runtime
// we sample 4 natives + 1 imposter, shuffle, and let the player pick.

export const IMPOSTER_PACKS = [
  {
    id: "boxing-70s",
    title: "Heavyweight champs of the 1970s",
    natives: [
      { name: "Joe Frazier", note: "champ 1970–1973" },
      { name: "Muhammad Ali", note: "champ 1974–1978" },
      { name: "George Foreman", note: "champ 1973–1974" },
      { name: "Ken Norton", note: "WBC champ 1978" },
      { name: "Leon Spinks", note: "beat Ali, Feb 1978" },
      { name: "Jimmy Ellis", note: "WBA champ 1968–1970" },
      { name: "Ernie Shavers", note: "fought Ali, 1977" },
    ],
    imposters: [
      { name: "Larry Holmes", note: "champ 1978–1985 — 80s run" },
      { name: "Mike Weaver", note: "WBA title, 1980" },
      { name: "Gerry Cooney", note: "vs Holmes, 1982" },
      { name: "Michael Spinks", note: "heavyweight champ, 1985" },
      { name: "Mike Tyson", note: "champ from 1986" },
      { name: "Trevor Berbick", note: "beat Ali, 1981" },
    ],
  },

  {
    id: "nba-90s",
    title: "NBA stars of the 1990s",
    natives: [
      { name: "Michael Jordan", note: "6 titles, 4 MVPs in the decade" },
      { name: "Hakeem Olajuwon", note: "back-to-back titles, 1994–95" },
      { name: "David Robinson", note: "MVP 1995" },
      { name: "Karl Malone", note: "MVP 1997" },
      { name: "Patrick Ewing", note: "Knicks Finals, 1994" },
      { name: "Charles Barkley", note: "MVP 1993" },
      { name: "Scottie Pippen", note: "Jordan's wingman" },
      { name: "Reggie Miller", note: "8 points in 9 seconds, 1995" },
      { name: "Penny Hardaway", note: "Magic Finals run, 1995" },
    ],
    imposters: [
      { name: "Tim Duncan", note: "rookie '97, dynasty 2000s" },
      { name: "Kobe Bryant", note: "drafted '96, prime 2000s" },
      { name: "Allen Iverson", note: "MVP 2001" },
      { name: "Shaquille O'Neal", note: "3-peat 2000–2002" },
      { name: "LeBron James", note: "drafted 2003" },
      { name: "Magic Johnson", note: "retired Nov 1991 — 80s era" },
      { name: "Larry Bird", note: "retired 1992 — 80s era" },
    ],
  },

  {
    id: "nfl-qb-80s",
    title: "Star NFL quarterbacks of the 1980s",
    natives: [
      { name: "Joe Montana", note: "4 Super Bowl wins" },
      { name: "Dan Marino", note: "MVP 1984, 48 TDs" },
      { name: "John Elway", note: "3 Super Bowl losses in the decade" },
      { name: "Jim McMahon", note: "Bears Super Bowl XX, Jan '86" },
      { name: "Phil Simms", note: "Giants Super Bowl XXI MVP" },
      { name: "Boomer Esiason", note: "Bengals MVP 1988" },
      { name: "Doug Williams", note: "Super Bowl XXII MVP, '88" },
      { name: "Ken Anderson", note: "Bengals MVP 1981" },
    ],
    imposters: [
      { name: "Troy Aikman", note: "Cowboys dynasty 1992–96" },
      { name: "Steve Young", note: "MVP 1992, 1994" },
      { name: "Brett Favre", note: "MVP run 1995–97" },
      { name: "Jim Kelly", note: "Bills Super Bowls 1991–94" },
      { name: "Warren Moon", note: "Oilers run-and-shoot, '91–93" },
    ],
  },

  {
    id: "nfl-qb-2000s",
    title: "Star NFL quarterbacks of the 2000s",
    natives: [
      { name: "Tom Brady", note: "3 Super Bowls in the decade" },
      { name: "Peyton Manning", note: "4 MVPs in the decade" },
      { name: "Donovan McNabb", note: "5 NFC title games" },
      { name: "Kurt Warner", note: "Super Bowl XXXIV, 2000" },
      { name: "Drew Brees", note: "Saints Super Bowl, Feb 2010" },
      { name: "Ben Roethlisberger", note: "Steelers Super Bowls, '06 & '09" },
      { name: "Eli Manning", note: "Super Bowl XLII MVP, '08" },
      { name: "Brett Favre", note: "Packers/Vikings late run" },
    ],
    imposters: [
      { name: "Aaron Rodgers", note: "Super Bowl XLV, Feb 2011" },
      { name: "Patrick Mahomes", note: "drafted 2017" },
      { name: "Russell Wilson", note: "drafted 2012" },
      { name: "Cam Newton", note: "MVP 2015" },
      { name: "Andrew Luck", note: "drafted 2012" },
      { name: "Joe Flacco", note: "Super Bowl MVP, Feb 2013" },
    ],
  },

  {
    id: "mlb-sluggers-90s",
    title: "MLB sluggers of the 1990s",
    natives: [
      { name: "Ken Griffey Jr.", note: "MVP 1997, 56 HRs" },
      { name: "Barry Bonds", note: "MVPs 1990, '92, '93" },
      { name: "Frank Thomas", note: "back-to-back MVPs, '93–'94" },
      { name: "Mark McGwire", note: "70 HRs in 1998" },
      { name: "Sammy Sosa", note: "MVP 1998, 66 HRs" },
      { name: "Juan Gonzalez", note: "MVPs 1996 & 1998" },
      { name: "Mike Piazza", note: "Mets/Dodgers; era's top hitting catcher" },
      { name: "Jeff Bagwell", note: "MVP 1994" },
      { name: "Albert Belle", note: "50/50 season, 1995" },
    ],
    imposters: [
      { name: "Albert Pujols", note: "ROY 2001, MVP run 2005–09" },
      { name: "Alex Rodriguez", note: "MVPs 2003, '05, '07" },
      { name: "Manny Ramirez", note: "peak 2001–08" },
      { name: "Vladimir Guerrero", note: "peak 2002–07" },
      { name: "David Ortiz", note: "Big Papi era 2003+" },
    ],
  },

  {
    id: "companies-2015",
    title: "Top US companies by market cap, 2015",
    natives: [
      { name: "Apple", note: "first $700B company" },
      { name: "Microsoft", note: "top 5 globally" },
      { name: "Google", note: "restructured to Alphabet, Aug 2015" },
      { name: "ExxonMobil", note: "top 10 — pre-shale-collapse oil king" },
      { name: "Berkshire Hathaway", note: "top 5" },
      { name: "Johnson & Johnson", note: "top 10" },
      { name: "Wells Fargo", note: "top 10 bank" },
      { name: "General Electric", note: "still top 10 in 2015" },
      { name: "Walmart", note: "top 10" },
      { name: "Amazon", note: "rising into top 15" },
    ],
    imposters: [
      { name: "US Steel", note: "1900s industrial titan" },
      { name: "Standard Oil", note: "early 1900s — broken up 1911" },
      { name: "Sears", note: "out of top 500 by 2015" },
      { name: "General Motors", note: "bankrupted 2009" },
      { name: "Tesla", note: "~$30B in 2015 — not top 50" },
      { name: "Nvidia", note: "~$10B in 2015 — not top 100" },
      { name: "Bethlehem Steel", note: "1950s steel #2" },
    ],
  },

  {
    id: "election-issues-1968",
    title: "Top US election issues, 1968",
    natives: [
      { name: "Vietnam War", note: "Tet Offensive, Jan–Feb '68" },
      { name: "civil rights", note: "MLK assassinated April 1968" },
      { name: "law and order", note: "Nixon's signature frame" },
      { name: "urban riots", note: "100+ cities erupt post-MLK" },
      { name: "the draft", note: "campus protests intensify" },
      { name: "the Great Society", note: "LBJ's contested program" },
      { name: "Wallace third party", note: "American Independent run" },
    ],
    imposters: [
      { name: "inflation", note: "1980's #1 issue" },
      { name: "Iran hostages", note: "1979–1981, pure Carter era" },
      { name: "gas lines", note: "OPEC '73, Iran '79" },
      { name: "Watergate", note: "broke 1972" },
      { name: "busing", note: "peaked 1971–76" },
      { name: "welfare reform", note: "peaked 1992–96, Clinton" },
      { name: "stagflation", note: "dominates 1973–82" },
    ],
  },

  {
    id: "box-office-80s",
    title: "Box office #1s of the 1980s",
    natives: [
      { name: "E.T.", note: "1982 #1, $359M domestic" },
      { name: "Return of the Jedi", note: "1983 #1" },
      { name: "The Empire Strikes Back", note: "1980 #1" },
      { name: "Indiana Jones and the Temple of Doom", note: "1984" },
      { name: "Beverly Hills Cop", note: "1984 yearly #1" },
      { name: "Back to the Future", note: "1985 #1" },
      { name: "Top Gun", note: "1986 #1" },
      { name: "Three Men and a Baby", note: "1987 #1" },
      { name: "Rain Man", note: "1988 #1" },
      { name: "Batman", note: "1989 #1" },
    ],
    imposters: [
      { name: "Titanic", note: "1997" },
      { name: "Jurassic Park", note: "1993 #1" },
      { name: "Forrest Gump", note: "1994 #1" },
      { name: "Home Alone", note: "Nov 1990" },
      { name: "Pretty Woman", note: "1990" },
      { name: "Terminator 2", note: "July 1991" },
      { name: "The Lion King", note: "1994" },
    ],
  },

  {
    id: "tv-90s",
    title: "Top TV shows of the 1990s",
    natives: [
      { name: "Cheers", note: "Nielsen #1, 1990–91" },
      { name: "Roseanne", note: "Nielsen #1, 1989–90" },
      { name: "Home Improvement", note: "Nielsen #1, 1993–94" },
      { name: "Seinfeld", note: "Nielsen #1 in '94–'95 and '97–'98" },
      { name: "ER", note: "Nielsen #1, 1995–97" },
      { name: "Friends", note: "top-5 from 1995" },
      { name: "Frasier", note: "top-10 mainstay" },
      { name: "60 Minutes", note: "Nielsen #1, 1991–92" },
      { name: "Touched by an Angel", note: "surprise top-5 hit" },
      { name: "Everybody Loves Raymond", note: "late-'90s rise" },
    ],
    imposters: [
      { name: "CSI", note: "premiered Oct 2000" },
      { name: "Lost", note: "premiered 2004" },
      { name: "Survivor", note: "premiered May 2000" },
      { name: "The Sopranos", note: "1999–2007 (peak is 2000s)" },
      { name: "The Cosby Show", note: "1984–1992 — 80s identity" },
      { name: "Dallas", note: "ended April 1991" },
      { name: "Will & Grace", note: "peak 2001–04" },
    ],
  },

  {
    id: "billboard-70s",
    title: "Chart-topping music acts of the 1970s",
    natives: [
      { name: "Elton John", note: "6 #1 albums in the decade" },
      { name: "Stevie Wonder", note: "Innervisions '73, Songs in the Key '76" },
      { name: "Led Zeppelin", note: "IV ('71), Houses ('73)" },
      { name: "Bee Gees", note: "Saturday Night Fever, 1977–78" },
      { name: "Eagles", note: "Hotel California, 1976–77" },
      { name: "Fleetwood Mac", note: "Rumours, 1977 (31 weeks at #1)" },
      { name: "Carole King", note: "Tapestry, 1971" },
      { name: "Pink Floyd", note: "Dark Side of the Moon, 1973" },
      { name: "The Carpenters", note: "multiple #1 singles" },
      { name: "Donna Summer", note: "disco era reigning queen" },
    ],
    imposters: [
      { name: "Madonna", note: "debut 1983" },
      { name: "Whitney Houston", note: "debut 1985" },
      { name: "Prince", note: "Purple Rain, 1984" },
      { name: "Hall & Oates", note: "peak 1981–84" },
      { name: "Bruce Springsteen", note: "Born in the U.S.A., 1984" },
      { name: "Michael Jackson", note: "Thriller, 1982" },
    ],
  },

  {
    id: "tech-titans-2010s",
    title: "Tech titans of the 2010s",
    natives: [
      { name: "Tim Cook", note: "Apple CEO from Aug 2011" },
      { name: "Jeff Bezos", note: "Amazon dominance decade" },
      { name: "Mark Zuckerberg", note: "Facebook IPO, May 2012" },
      { name: "Elon Musk", note: "Tesla Model S, 2012" },
      { name: "Sundar Pichai", note: "Google CEO, Aug 2015" },
      { name: "Satya Nadella", note: "Microsoft CEO, Feb 2014" },
      { name: "Jack Dorsey", note: "Twitter / Square" },
      { name: "Reed Hastings", note: "Netflix streaming pivot" },
      { name: "Travis Kalanick", note: "Uber CEO until 2017" },
      { name: "Jensen Huang", note: "Nvidia / AI emergence" },
    ],
    imposters: [
      { name: "Steve Jobs", note: "died Oct 2011" },
      { name: "Bill Gates", note: "left Microsoft chair, Feb 2014" },
      { name: "Steve Ballmer", note: "Microsoft CEO until Feb 2014" },
      { name: "Andy Grove", note: "left Intel chair, 2005" },
      { name: "Marissa Mayer", note: "Yahoo identity is 1990s" },
    ],
  },
];
